/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ExampleInterface extends Interface {
  getFunction(
    nameOrSignature: "increase" | "initialValue" | "number"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "increase", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "number", values?: undefined): string;

  decodeFunctionResult(functionFragment: "increase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "number", data: BytesLike): Result;
}

export interface Example extends BaseContract {
  connect(runner?: ContractRunner | null): Example;
  waitForDeployment(): Promise<this>;

  interface: ExampleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  increase: TypedContractMethod<[], [void], "nonpayable">;

  initialValue: TypedContractMethod<[_num: BigNumberish], [void], "nonpayable">;

  number: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "increase"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initialValue"
  ): TypedContractMethod<[_num: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "number"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
